import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head"

import FormInputs from "../components/FormInputs";
import RenderChart from "../components/RenderChart";

import type { Temperatures } from "../components/FormInputs";

const Home: NextPage = () => {
	
	const [loading, setLoading] = useState(false);
	const [temperatures, setTemperatures] = useState<Temperatures>();

	return (
		<>
		<Head>
			<title>Watz Tha Wetha</title>
			<meta name="description" content="Generated by create-t3-app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
			<div className="container min-h-screen flex flex-col items-center  gap-12 px-4 py-16 ">
				<h1 className="text-7xl font-bold text-white font-['Righteous']">Watz Tha Wetha</h1>
				<FormInputs
					loading={loading}
					setLoading={setLoading}
					setTemperatures={setTemperatures}
				/>
				{ temperatures && <RenderChart chartData={temperatures} />}
			</div>
		</main>
		</>
	);
};

export default Home;
